// System icons metadata
export const SYSTEM_ICONS = [
  "IconAlert",
  "IconAlertCircle",
  "IconAlertFilled",
  "IconArrowBack",
  "IconArrowForward",
  "IconBadgeCheckFilled",
  "IconBell",
  "IconBellFilled",
  "IconBook",
  "IconBookFilled",
  "IconBookmark",
  "IconBookmarkFilled",
  "IconCalculator",
  "IconCalculator2",
  "IconCalculatorFilled",
  "IconCalculatorFilled2",
  "IconCamera",
  "IconCameraFilled",
  "IconChat",
  "IconChatFilled",
  "IconChatFilled1",
  "IconCheck",
  "IconCheckCircle",
  "IconCheckCircleFilled",
  "IconChemistry",
  "IconChevronBack",
  "IconChevronDown",
  "IconChevronForward",
  "IconChevronUp",
  "IconClose",
  "IconCreditCard",
  "IconCreditCardFilled",
  "IconCrown",
  "IconCrownFilled",
  "IconDelete",
  "IconDeleteFilled",
  "IconDislike",
  "IconDislikeFilled",
  "IconDownload",
  "IconEdit",
  "IconEditFilled",
  "IconEnvelope",
  "IconEnvelopeFilled",
  "IconFeedback",
  "IconFeedbackFilled",
  "IconFilter",
  "IconHelp",
  "IconHelpFilled",
  "IconHome",
  "IconHomeFilled",
  "IconInfo",
  "IconInfoFilled",
  "IconKebabMenu",
  "IconLike",
  "IconLikeFilled",
  "IconLoader",
  "IconLogout",
  "IconMaths",
  "IconNegativeCircleFilled",
  "IconPadlockLocked",
  "IconPencilHand",
  "IconPhysics",
  "IconPin",
  "IconReset",
  "IconRotateScreen",
  "IconSearch",
  "IconShare",
  "IconShareArrow",
  "IconShareArrowFilled",
  "IconSikkay",
  "IconSikkayFilled",
  "IconSmiley",
  "IconSmileyFilled",
  "IconSort",
  "IconStar",
  "IconStarFilled",
  "IconTest",
  "IconTestFilled",
  "IconVideoPlay",
  "IconVideoPlayFilled",
  "IconWhatsapp",
  "IconWrenchGear",
] as const;

// Illustration icons metadata
export const ILLUSTRATION_ICONS = [
  "IllustrationAvatarFemale",
  "IllustrationAvatarGeneric",
  "IllustrationAvatarMale",
  "IllustrationDoubtsolve",
  "IllustrationGiki",
  "IllustrationIba",
  "IllustrationLiveSessions",
  "IllustrationLogoMaqsad",
  "IllustrationLogoMaqsad512BgWhite",
  "IllustrationLums",
  "IllustrationMissHumaConfused",
  "IllustrationNotes",
  "IllustrationNotes2",
  "IllustrationSikka",
  "IllustrationTests",
  "IllustrationVideoLectures",
] as const;

export type SystemIconName = (typeof SYSTEM_ICONS)[number];
export type IllustrationIconName = (typeof ILLUSTRATION_ICONS)[number];

export const ILLUSTRATION_VARIANTS = [
  "primary",
  "secondary",
  "dark",
  "light",
] as const;

export type IllustrationVariant = (typeof ILLUSTRATION_VARIANTS)[number];
